"""Added image_url to Vehicle

Revision ID: 59b33a98c3d9
Revises: 77068c9c40ae
Create Date: 2024-05-11 16:37:43.452175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59b33a98c3d9'
down_revision = '77068c9c40ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
